### ISSUE TITLE
calculation of rad_extraterr_hourly: midpoint of hour

### ISSUE THREAD

**Issue by juliuseberhard** [tpilz/echse_engines#1]
In file ./processes/meteo/meteo.h, line 454:
Calculation of rad_extraterr_hourly follows the procedure explained in FAO, _Crop evaporation - Guidelines for computing crop water requirements_, chapter 3: Meteorological data (link: http://www.fao.org/docrep/X0490E/x0490e07.htm#calculation%20procedures). Eq. (31) in the document uses "standard clock time at the midpoint of period [hour]." Depending on whether radiation values are referring to the beginning (past=false) or the end of a period (past=true), line 454 should read
`double hour_mid = hour + 0.5;` (if past=false) or
`double hour_mid = hour - 0.5;` (if past=true), respectively.

grüße von nebenan,
Julius

**Comment by tpilz** [comment]
How to set the 'past' flag is a matter of time series input pre-processing. The flag is used by the ECHSE core to define the way the time series input is handled internally. In an engine, it is not possible to consider this flag explicitly and, furthermore, it should not matter as long as the pre-processing as been done correctly.
